tx_guard_time = 500

[mqtt]
broker = "{{ mqtt_broker }}"
username = "remote_closedown"
password = "{{ secrets.mqtt_passwords.remote_closedown }}"
client_id = "remote-closedown-{{ transmitter_callsign }}"
status_topic = "{{ transmitter_callsign }}/remote_closedown/status"
command_topic = "{{ transmitter_callsign }}/remote_closedown/command"

[tx_power_enable]
number = 22
inverted = true

# [tx_power_status]
# number = 9
# inverted = true

[ptt_enable]
number = 27
inverted = true

# [ptt_status]
# number = 10
# inverted = true
