---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: dannixon/ansible-testing/actions/lint@main
